name:                grasana
version:             0.1.0.0
github:              "gfarrell/grasana"
license:             BSD3
author:              "Gideon Farrell"
maintainer:          "gideon@gtf.io"
copyright:           "2021 Gideon Farrell"

extra-source-files:
- README.md
- ChangeLog.md

description: Tool for rendering Asana projects as graphs

dependencies:
- aeson >= 1.5 && < 2.0
- async >= 2.0 && < 3.0
- base >= 4.7 && < 5
- blaze-html >= 0.9 && < 0.10
- bytestring >= 0.10 && < 0.12
- hashmap >= 1.3 && < 2
- hspec >= 2.7 && < 3
- http-conduit >= 2.3 && < 3
- http-types >= 0.10 && < 0.20
- shakespeare >= 2 && < 3
- text >= 1.2 && < 2.0
- utf8-string >= 1.0 && < 2.0
- vector >= 0.10 && < 0.20
- word-wrap >= 0.4 && < 0.5
- yaml >= 0.10 && < 0.12

library:
  source-dirs: src

executables:
  grasana:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grasana

tests:
  grasana-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grasana
    - hspec
