name:                grasana-server
version:             0.1.0.0
github:              "gfarrell/grasana"
license:             BSD3
author:              "Gideon Farrell"
maintainer:          "gideon@gtf.io"
copyright:           "2021 Gideon Farrell"

extra-source-files:
- README.md
- ChangeLog.md

description: Backend server for Grasana, a tool for exploring Asana projects graphically

dependencies:
- base >= 4.7 && < 5
- hashmap >= 1.3 && < 2
- http-conduit >= 2.3 && < 3
- hspec >= 2.7 && < 3
- aeson >= 1.5 && < 2.0
- bytestring >= 0.10 && < 0.12
- yaml >= 0.10 && < 0.12
- utf8-string >= 1.0 && < 2.0
- yesod >= 1.6 && < 2.0
- text >= 1.2 && < 2.0
- http-types >= 0.10 && < 0.20
- vector >= 0.10 && < 0.20

library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grasana-server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - grasana-server
    - hspec
